#cloud-config
package_upgrade: true
packages:
  - linux-modules-extra-azure
  - emacs
  - iperf
  - iperf3
  - net-tools
runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - az login --identity
  - Agent1Eth1MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth1PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent1Eth2MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth2PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth1MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth1PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth2MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth2PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - sed -i "s/Agent1Eth1MacAddress/$Agent1Eth1MacAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth2MacAddress/$Agent1Eth2MacAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json    
  - sed -i "s/Agent2Eth1MacAddress/$Agent2Eth1MacAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth2MacAddress/$Agent2Eth2MacAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json
  - Agent1Eth1IpAddress=${Agent1Eth1PrivateIpAddresses[0]}
  - Agent1Eth2IpAddress=${Agent1Eth2PrivateIpAddresses[0]}
  - Agent2Eth0IpAddress=${Agent2Eth0IpAddress}
  - Agent2Eth1IpAddress=${Agent2Eth1PrivateIpAddresses[0]}
  - Agent2Eth2IpAddress=${Agent2Eth2PrivateIpAddresses[0]}
  - sed -i "s/Agent1Eth1IpAddress/$Agent1Eth1IpAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth2IpAddress/$Agent1Eth2IpAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json    
  - sed -i "s/Agent2Eth0IpAddress/$Agent2Eth0IpAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth1IpAddress/$Agent2Eth1IpAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth2IpAddress/$Agent2Eth2IpAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoConfigPath}/*.json
  - modprobe mana_ib
  - AgentEth1MacAddress=$(cat /sys/class/net/eth1/address)
  - AgentEth2MacAddress=$(cat /sys/class/net/eth2/address)
  - sed -i "s/mac@eth1/$AgentEth1MacAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoExecDeployPath}/docker-compose.yaml
  - sed -i "s/mac@eth2/$AgentEth2MacAddress/g" /home/${UserName}/${GitRepoName}/${GitRepoExecDeployPath}/docker-compose.yaml
  - AgentBusInfoList=$(lshw -C network -json | jq '.[] | select( .businfo != null)' | jq -r .businfo)
  - AgentEth1BusInfo=$(echo $AgentBusInfoList | awk '{print $1}')
  - AgentEth2BusInfo=$(echo $AgentBusInfoList | awk '{print $2}')
  - sed -i "s/pci@eth1/$AgentEth1BusInfo/g" /home/${UserName}/${GitRepoName}/${GitRepoExecDeployPath}/docker-compose.yaml
  - sed -i "s/pci@eth2/$AgentEth2BusInfo/g" /home/${UserName}/${GitRepoName}/${GitRepoExecDeployPath}/docker-compose.yaml
  - AgentEth1VmBus=$(readlink /sys/class/net/eth1/device | xargs basename)
  - AgentEth2VmBus=$(readlink /sys/class/net/eth2/device | xargs basename)
  - sed -i "s/vmbus@eth1/$AgentEth1VmBus/g" /home/${UserName}/${GitRepoName}/${GitRepoExecDeployPath}/docker-compose.yaml
  - sed -i "s/vmbus@eth2/$AgentEth2VmBus/g" /home/${UserName}/${GitRepoName}/${GitRepoExecDeployPath}/docker-compose.yaml
  - /home/${UserName}/${GitRepoName}/${GitRepoExecDeployPath}/setup.sh
  - make docker-compose -C /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/Docker
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]