apiVersion: v1
kind: ConfigMap
metadata:
    name: ixiatg-release-config
    namespace: ixiatg-op-system
data:
    versions: |
        {
          "release": "local-latest",
          "images": [
                {
                    "name": "controller",
                    "path": "ghcr.io/open-traffic-generator/keng-controller",
                    "tag": "0.1.0-53"
                },
                {
                    "name": "gnmi-server",
                    "path": "ghcr.io/open-traffic-generator/otg-gnmi-server",
                    "tag": "1.13.0"
                },
                {
                    "name": "traffic-engine",
                    "path": "ghcr.io/open-traffic-generator/ixia-c-traffic-engine",
                    "tag": "1.6.0.85"
                },
                {
                    "name": "protocol-engine",
                    "path": "ghcr.io/open-traffic-generator/ixia-c-protocol-engine",
                    "tag": "1.00.0.337"
                }
            ]
        }
